volumes:
  static_production:
  pg_data_production:
  media_production:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: ajiexdev/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_production:/back_static
      - media_production:/media
  
  frontend:
    image: ajiexdev/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_production:/front_static

  nginx:
    image: ajiexdev/foodgram_nginx
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_production:/static_files
      - media_production:/media
    ports:
      - 8080:80
