# Generated by Django 3.2.16 on 2024-11-28 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0005_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='recipes',
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.abstractuser'),
            preserve_default=False,
        ),
    ]
