# Generated by Django 3.2.16 on 2024-11-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_auto_20241129_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
    ]
