# Generated by Django 3.2.16 on 2024-11-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_remove_follow_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='author',
        ),
    ]
