# Generated by Django 3.2.16 on 2024-12-10 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Slug должен содержать только буквы, цифры и дефисы.', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Тег'),
        ),
    ]
