# Generated by Django 5.1.4 on 2024-12-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['recipe'], 'verbose_name': 'Список покупки', 'verbose_name_plural': 'Список покупок'},
        ),
    ]
