# Generated by Django 3.2.16 on 2024-12-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='127.0.0.1/recipes/images/', verbose_name='Изображение'),
        ),
    ]
