# Generated by Django 3.2.16 on 2024-11-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='image',
            field=models.ImageField(default=1, upload_to='foodgram/users/images/'),
            preserve_default=False,
        ),
    ]
