# Generated by Django 3.2.16 on 2024-11-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_abstractuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractuser',
            old_name='image',
            new_name='avatar',
        ),
    ]
